development:
  adapter: postgis
  encoding: unicode
  database: matos_development
  pool: 5
  username: matos
  password:
  script_dir: /usr/share/pgsql/contrib/postgis
  schema_search_path: public,postgis

test: &test
  adapter: postgis
  encoding: unicode
  database: matos_test
  pool: 5
  username: matos
  password:
  script_dir: /usr/share/pgsql/contrib/postgis
  schema_search_path: public,postgis

staging:
  adapter: postgis
  encoding: unicode
  database: matos_staging
  port: 5432
  pool: 5
  username: matos
  password:
  script_dir: /usr/pgsql-9.2/share/contrib/postgis-2.0
  schema_search_path: public,postgis
  template: template0

production:
  adapter: postgis
  encoding: unicode
  database: matos_production
  port: 5432
  pool: 5
  username: matos
  password:
  script_dir: /usr/pgsql-9.2/share/contrib/postgis-2.0
  schema_search_path: public,postgis
  template: template0

cucumber:
  <<: *test
