development:
  adapter: postgis
  encoding: unicode
  database: matos_development
  pool: 5
  username: matos
  password:
  postgis_extension: postgis,pg_trgm
  schema_search_path: public,postgis

test: &test
  adapter: postgis
  encoding: unicode
  database: matos_test
  pool: 5
  username: matos
  password:
  postgis_extension: postgis,pg_trgm
  schema_search_path: public,postgis

staging:
  adapter: postgis
  encoding: unicode
  database: matos_staging
  port: 5432
  pool: 5
  username: matos
  password:
  postgis_extension: postgis,pg_trgm
  schema_search_path: public,postgis

production:
  adapter: postgis
  encoding: unicode
  database: matos_production
  port: 5432
  pool: 5
  username: matos
  password:
  postgis_extension: postgis,pg_trgm
  schema_search_path: public,postgis

cucumber:
  <<: *test
